services:
  - type: web
    name: merigarage
    runtime: docker
    plan: free
    branch: main
    envVars:
      - key: APP_NAME
        value: MeriGarage
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:NjEnxP9Oimzcw4z41fJBSUI0Ovvdv7fL8NpRPVyregA=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: merigarage-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: merigarage-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: merigarage-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: merigarage-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: merigarage-db
          property: password
      - key: SESSION_DRIVER
        value: file
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.hostinger.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_ENCRYPTION
        value: ssl
      - key: MAIL_USERNAME
        value: alert@merigarage.com
      - key: MAIL_PASSWORD
        value: Ajay2050#@
      - key: MAIL_FROM_ADDRESS
        value: alert@merigarage.com
      - key: MASTER_LOGIN_ENABLED
        value: true
      - key: MASTER_LOGIN_PASSWORD
        value: master@123
      - key: WEBSITE_URL
        value: https://merigarage.com/software

databases:
  - name: merigarage-db
    databaseName: garagemanagement
    user: merigarage_user
    plan: free
